# User roles
PROPERTY_MANAGER = "PROPERTY_MANAGER"
PROPERTY_DEVELOPER = "PROPERTY_DEVELOPER"
PROJECT_MANAGER = "PROJECT_MANAGER"
HOA_CONDO_BOARD = "HOA_CONDO_BOARD"
ARCHITECT = "ARCHITECT"
GENERAL_CONTRACTOR = "GENERAL_CONTRACTOR"
CONSULTANT = "CONSULTANT"
CONSTRUCTION_MANAGER = "CONSTRUCTION_MANAGER"
FINANCIAL_ANALYST = "FINANCIAL_ANALYST"
OTHER = "OTHER"

# Seller Roles
SALES_MARKETING = "SALES_MARKETING"
ENGINEERING = "ENGINEERING"
CONSULTING = "CONSULTING"

TEAM_ROLES_CHOICES = (
    (PROPERTY_MANAGER, "Property Manager"),
    (PROPERTY_DEVELOPER, "Property Developer"),
    (PROJECT_MANAGER, "Project Manager"),
    (HOA_CONDO_BOARD, "HOA or Condo Board"),
    (ARCHITECT, "Architect"),
    (GENERAL_CONTRACTOR, "General Contractor"),
    (CONSULTANT, "Consultant"),
    (CONSTRUCTION_MANAGER, "Construction Manager"),
    (FINANCIAL_ANALYST, "Financial Analyst"),
    (OTHER, "Other"),
    # sellers
    (SALES_MARKETING, "Sales/Marketing"),
    (ENGINEERING, "Engineering"),
    (CONSULTING, "Consulting"),
)


# RFP constants
ACTIVE = "ACTIVE"
INACTIVE = "INACTIVE"
RFP_CHOICES = (
    (ACTIVE, "Active"),
    (INACTIVE, "Inactive"),
)

# for proposals
IN_DRAFT = "IN_DRAFT"
SUBMITTED_FOR_REVIEW = "SUBMITTED_FOR_REVIEW"
ARCHIVED = "ARCHIVED"
CHANGES_REQUESTED = "CHANGES_REQUESTED"
ACCEPTED = "ACCEPTED"
DECLINED = "DECLINED"

STATUSES = [IN_DRAFT, SUBMITTED_FOR_REVIEW, ARCHIVED]
STATUS_CHOICES = (
    (IN_DRAFT, "In Draft"),
    (SUBMITTED_FOR_REVIEW, "Submitted For Review"),
    (ARCHIVED, "Archived"),
    (CHANGES_REQUESTED, "Changes Requested"),
    (ACCEPTED, "Accepted"),
    (DECLINED, "Declined"),
)
STATUS_DEV_CHOICES = [
    SUBMITTED_FOR_REVIEW,
    ARCHIVED,
    CHANGES_REQUESTED,
    ACCEPTED,
    DECLINED,
]
