PENDING = "PENDING"
READ = "READ"

NOTIFICATION_STATUSES = [PENDING, READ]

NOTIFICATION_STATUS_CHOICES = (
    (PENDING, "Pending"),
    (READ, "Read"),
)

NEW_MESSAGE = "NEW_MESSAGE"
NEW_PROPOSAL = "NEW_PROPOSAL"
NEW_PROJECT = "NEW_PROJECT"
PROJECT_UPDATE = "PROJECT_UPDATE"

NOTIFICATION_TYPE_CHOICES = (
    (NEW_MESSAGE, "New Message"),
    (NEW_PROPOSAL, "New Proposal"),
    (NEW_PROJECT, "New Project"),
    (PROJECT_UPDATE, "Project Update"),
)
