# Generated by Django 4.2.3 on 2023-11-20 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_customuser_about_customuser_is_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User"},
        ),
        migrations.AddField(
            model_name="customuser",
            name="references",
            field=models.ManyToManyField(blank=True, to="core.reference"),
        ),
    ]
