# Generated by Django 4.2.3 on 2023-08-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="all_time_revenue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="linkedin_profile",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="market_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                default="PUBLIC",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_fit_score",
            field=models.IntegerField(default=0),
        ),
    ]
