# Generated by Django 4.2.3 on 2023-08-04 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YTDStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                ("is_removed", models.BooleanField(default=False)),
                ("quota_verified", models.BooleanField()),
                (
                    "quarter",
                    models.PositiveIntegerField(
                        choices=[(1, "Q1"), (2, "Q2"), (3, "Q3"), (4, "Q4")]
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("market", models.CharField(max_length=100)),
                (
                    "quota_attainment_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "average_deal_size",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("average_sales_cycle", models.PositiveIntegerField()),
                ("leaderboard_rank", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "YTD Stats",
            },
        ),
        migrations.CreateModel(
            name="CareerStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                ("is_removed", models.BooleanField(default=False)),
                ("quota_verified", models.BooleanField()),
                ("year", models.PositiveIntegerField()),
                ("company", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("market", models.CharField(max_length=100)),
                (
                    "quota_attainment_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "average_deal_size",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("average_sales_cycle", models.PositiveIntegerField()),
                ("leaderboard_rank", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Career Stats",
            },
        ),
    ]
