# Generated by Django 4.2.3 on 2023-12-03 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                ("is_removed", models.BooleanField(default=False)),
                ("quota_verified", models.BooleanField(default=False)),
                ("year", models.PositiveIntegerField(default=2024)),
                (
                    "quarter",
                    models.PositiveIntegerField(
                        choices=[(1, "Q1"), (2, "Q2"), (3, "Q3"), (4, "Q4")], default=1
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            (
                                "Chief Revenue Officer (CRO)",
                                "Chief Revenue Officer (CRO)",
                            ),
                            (
                                "Chief Marketing Officer (CMO)",
                                "Chief Marketing Officer (CMO)",
                            ),
                            ("VP of Sales", "VP of Sales"),
                            ("Head of Sales", "Head of Sales"),
                            ("Account Executive", "Account Executive"),
                            ("Sr. Account Executive", "Sr. Account Executive"),
                            (
                                "Strategic Account Executive",
                                "Strategic Account Executive",
                            ),
                            (
                                "Mid Market Account Executive",
                                "Mid Market Account Executive",
                            ),
                            (
                                "Enterprise Account Executive",
                                "Enterprise Account Executive",
                            ),
                            ("Director of Marketing", "Director of Marketing"),
                            ("Sr. Director of Marketing", "Sr. Director of Marketing"),
                            ("Product Marketing Manager", "Product Marketing Manager"),
                            ("Market Research Analyst", "Market Research Analyst"),
                            ("Sales Manager", "Sales Manager"),
                            (
                                "Sales Development Representative",
                                "Sales Development Representative",
                            ),
                            (
                                "Business Development Representative",
                                "Business Development Representative",
                            ),
                            (
                                "Business Development Manager",
                                "Business Development Manager",
                            ),
                            ("Brand Manager", "Brand Manager"),
                            ("Marketing Coordinator", "Marketing Coordinator"),
                            ("Content Strategist", "Content Strategist"),
                            ("Customer Success Manager", "Customer Success Manager"),
                            (
                                "Sr. Customer Success Manager",
                                "Sr. Customer Success Manager",
                            ),
                            ("Market Strategist", "Market Strategist"),
                            ("Channel Sales Manager", "Channel Sales Manager"),
                            ("Partner Manager", "Partner Manager"),
                            (
                                "Sales Enablement Specialist",
                                "Sales Enablement Specialist",
                            ),
                            (
                                "Customer Experience Manager",
                                "Customer Experience Manager",
                            ),
                            ("Data Analyst", "Data Analyst"),
                            ("User Acquisition Manager", "User Acquisition Manager"),
                            (
                                "Demand Generation Specialist",
                                "Demand Generation Specialist",
                            ),
                            ("SDR Manager", "SDR Manager"),
                            ("BDR Manager", "BDR Manager"),
                            ("Other", "Other"),
                        ],
                        default="Account Executive",
                        max_length=100,
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("Consumer", "Consumer Direct Sales"),
                            ("Small Business", "SMB (Small Business) Sales"),
                            ("Mid Market", "Mid-Market Sales"),
                            ("Enterprise", "Enterprise Sales"),
                            ("Business Development", "Business Development"),
                        ],
                        default="Small Business",
                        max_length=100,
                    ),
                ),
                ("quota", models.IntegerField(default=0)),
                (
                    "quota_attainment_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "average_deal_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("average_sales_cycle", models.IntegerField(blank=True, null=True)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("IT", "Information Technology (IT) Services"),
                            ("CYBERSECURITY", "Cybersecurity"),
                            ("SAAS", "Software as a Service (SaaS)"),
                            (
                                "AI_ML",
                                "Artificial Intelligence (AI) and Machine Learning (ML)",
                            ),
                            ("HARDWARE", "Hardware"),
                            ("TELECOMMUNICATIONS", "Telecommunications"),
                            ("E_COMMERCE", "E-commerce Platforms"),
                            ("EDTECH", "EdTech"),
                            ("FINTECH", "FinTech"),
                            ("HEALTHTECH", "HealthTech/MedTech"),
                            ("ERP", "Enterprise Resource Planning (ERP) Systems"),
                            ("SOCIAL_MEDIA", "Social Media Platforms"),
                            ("BIG_DATA", "Big Data and Analytics"),
                            ("IOT", "Internet of Things (IoT)"),
                            ("AR_VR", "Augmented Reality (AR)/Virtual Reality (VR)"),
                            ("BLOCKCHAIN", "Blockchain and Cryptocurrency"),
                            ("CLEANTECH", "CleanTech"),
                            ("CLOUD_SERVICES", "Cloud Services"),
                            ("GAMING", "Gaming"),
                            ("5G", "5G Technology"),
                            ("ADTECH", "AdTech"),
                            ("PHARMACEUTICAL", "Pharmaceutical"),
                            ("MEDICAL_DEVICES", "Medical Devices"),
                            ("AUTOMOTIVE", "Automotive"),
                            ("REAL_ESTATE", "Real Estate"),
                            ("RETAIL", "Retail"),
                            ("WHOLESALE_TRADE", "Wholesale Trade"),
                            ("INSURANCE", "Insurance"),
                            ("FINANCIAL_SERVICES", "Financial Services"),
                            ("CPG", "Consumer Packaged Goods (CPG)"),
                            ("FOOD_BEVERAGE", "Food and Beverage"),
                            ("HOSPITALITY", "Hospitality"),
                            ("TRAVEL_TOURISM", "Travel and Tourism"),
                            ("SPORTS_ENTERTAINMENT", "Sports and Entertainment"),
                            ("PUBLISHING_MEDIA", "Publishing and Media"),
                            ("ADVERTISING_MARKETING", "Advertising and Marketing"),
                            ("APPAREL_FASHION", "Apparel and Fashion"),
                            ("FURNITURE_DECOR", "Furniture and Home Decor"),
                            ("CONSTRUCTION", "Construction and Building Materials"),
                            (
                                "INDUSTRIAL_MANUFACTURING",
                                "Industrial and Manufacturing",
                            ),
                            ("ENERGY_UTILITIES", "Energy and Utilities"),
                            ("AEROSPACE_DEFENSE", "Aerospace and Defense"),
                            ("AGRICULTURE", "Agriculture"),
                            (
                                "TRANSPORTATION_LOGISTICS",
                                "Transportation and Logistics",
                            ),
                            ("EDUCATION", "Education"),
                            ("FITNESS_WELLNESS", "Fitness and Wellness"),
                            ("PROFESSIONAL_SERVICES", "Professional Services"),
                            ("NONPROFIT", "Nonprofit Sector"),
                            ("COSMETICS_PERSONAL_CARE", "Cosmetics and Personal Care"),
                            ("LUXURY_GOODS_JEWELRY", "Luxury Goods and Jewelry"),
                            ("PET_PRODUCTS_SERVICES", "Pet Products and Services"),
                            ("ENVIRONMENTAL_SERVICES", "Environmental Services"),
                            ("WINE_SPIRITS", "Wine and Spirits"),
                        ],
                        default="IT",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stats",
            },
        ),
    ]
