# Generated by Django 4.2.3 on 2024-01-15 19:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0002_stat"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AwardRecognition",
            new_name="Award",
        ),
        migrations.RemoveField(
            model_name="ytdstat",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="award",
            options={"verbose_name_plural": "Awards"},
        ),
        migrations.DeleteModel(
            name="CareerStat",
        ),
        migrations.DeleteModel(
            name="YTDStat",
        ),
    ]
