# Generated by Django 4.2.3 on 2023-10-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_remove_careerstats_quarter_careerstats_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ytdstats",
            name="leaderboard_rank",
        ),
        migrations.AlterField(
            model_name="careerstats",
            name="average_deal_size",
            field=models.CharField(
                choices=[
                    ("5k - 10k", "5k - 10k"),
                    ("10k - 20k", "10k - 20k"),
                    ("20k - 30k", "20k - 30k"),
                    ("30k - 40k", "30k - 40k"),
                    ("40k - 50k", "40k - 50k"),
                    ("50k - 60k", "50k - 60k"),
                    ("60k - 70k", "60k - 70k"),
                    ("70k - 80k", "70k - 80k"),
                    ("80k - 90k", "80k - 90k"),
                    ("90k - 100k", "90k - 100k"),
                    ("> 100k", "> 100k"),
                ],
                default="5k - 10k",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="careerstats",
            name="market",
            field=models.CharField(
                choices=[
                    ("Consumer", "Consumer Direct Sales"),
                    ("Small Business", "SMB (Small Business) Sales"),
                    ("Mid Market", "Mid-Market Sales"),
                    ("Enterprise", "Enterprise Sales"),
                    ("Business Development", "Business Development"),
                ],
                default="Small Business",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ytdstats",
            name="average_deal_size",
            field=models.CharField(
                choices=[
                    ("5k - 10k", "5k - 10k"),
                    ("10k - 20k", "10k - 20k"),
                    ("20k - 30k", "20k - 30k"),
                    ("30k - 40k", "30k - 40k"),
                    ("40k - 50k", "40k - 50k"),
                    ("50k - 60k", "50k - 60k"),
                    ("60k - 70k", "60k - 70k"),
                    ("70k - 80k", "70k - 80k"),
                    ("80k - 90k", "80k - 90k"),
                    ("90k - 100k", "90k - 100k"),
                    ("> 100k", "> 100k"),
                ],
                default="5k - 10k",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ytdstats",
            name="market",
            field=models.CharField(
                choices=[
                    ("Consumer", "Consumer Direct Sales"),
                    ("Small Business", "SMB (Small Business) Sales"),
                    ("Mid Market", "Mid-Market Sales"),
                    ("Enterprise", "Enterprise Sales"),
                    ("Business Development", "Business Development"),
                ],
                default="Small Business",
                max_length=100,
            ),
        ),
    ]
