# Generated by Django 4.2.3 on 2023-10-04 03:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_remove_ytdstats_leaderboard_rank_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careerstats",
            name="leaderboard_rank",
        ),
    ]
