# Generated by Django 4.2.3 on 2023-10-22 18:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0006_remove_careerstats_leaderboard_rank"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CareerStats",
            new_name="CareerStat",
        ),
        migrations.RenameModel(
            old_name="YTDStats",
            new_name="YTDStat",
        ),
    ]
