# Generated by Django 4.2.3 on 2023-11-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0008_alter_careerstat_title_alter_ytdstat_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerstat",
            name="quota",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ytdstat",
            name="quota",
            field=models.IntegerField(default=0),
        ),
    ]
